package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

type nativeBuildHook struct {
	id          string
	matcher     string
	command     string
	script      string
	instruction string
	prompt      string
	event       string
	timeout     int
	failClosed  bool
	blocking    bool
	ifCondition string
	section     string
	typeName    string
	description string
}

type nativeAmpHookEntry struct {
	ID         string `json:"id"`
	Command    string `json:"command,omitempty"`
	Script     string `json:"script,omitempty"`
	Timeout    int    `json:"timeout"`
	FailClosed bool   `json:"failClosed"`
	If         string `json:"if,omitempty"`
}

type nativeAmpHookGroup struct {
	name    string
	entries []nativeAmpHookEntry
}

func runNativeBuildAmp(root string, out io.Writer) error {
	start := time.Now()
	fmt.Fprintf(out, "\n%s\n\n", ansiBold("loaf build"))

	sharedStart := time.Now()
	fmt.Fprintf(out, "  %s shared skills intermediate...", ansiCyan("building"))
	if err := buildNativeSharedSkillsIntermediate(root); err != nil {
		fmt.Fprintf(out, "\r  %s shared skills intermediate\n", ansiRed("✗"))
		return err
	}
	fmt.Fprintf(out, "\r  %s shared skills intermediate %s\n", ansiGreen("✓"), ansiGray("("+elapsedSeconds(sharedStart)+")"))

	targetStart := time.Now()
	fmt.Fprintf(out, "  %s amp...", ansiCyan("building"))
	if err := buildNativeAmpTarget(root); err != nil {
		fmt.Fprintf(out, "\r  %s amp\n", ansiRed("✗"))
		return err
	}
	fmt.Fprintf(out, "\r  %s amp %s\n", ansiGreen("✓"), ansiGray("("+elapsedSeconds(targetStart)+")"))
	fmt.Fprintln(out)
	fmt.Fprintf(out, "%s %s\n", ansiGreen("Build complete"), ansiGray("("+elapsedSeconds(start)+")"))
	return nil
}

func buildNativeAmpTarget(root string) error {
	version, err := nativeBuildPackageVersion(root)
	if err != nil {
		return err
	}
	targetsConfig, err := readNativeBuildTargetsConfig(root)
	if err != nil {
		return err
	}
	dist := filepath.Join(root, "dist", "amp")
	if err := os.RemoveAll(dist); err != nil {
		return err
	}
	if err := copyNativeBuildSkills(nativeBuildSkillCopyOptions{
		srcDir:        filepath.Join(root, "dist"),
		destDir:       filepath.Join(dist, "skills"),
		targetName:    "amp",
		version:       version,
		targetsConfig: targetsConfig,
		transformMd:   func(content string) string { return substituteNativeBuildHarnessLanguage(content, "amp") },
	}); err != nil {
		return err
	}
	return generateNativeAmpPlugin(filepath.Join(root, "config", "hooks.yaml"), dist, version)
}

func generateNativeAmpPlugin(hooksPath string, dist string, version string) error {
	hooks, err := readNativeBuildHooks(hooksPath)
	if err != nil {
		return err
	}
	pluginDir := filepath.Join(dist, ".amp", "plugins")
	if err := os.MkdirAll(pluginDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(pluginDir, "loaf.ts"), []byte(renderNativeAmpPlugin(hooks, version)), 0o644)
}

func renderNativeAmpPlugin(hooks []nativeBuildHook, version string) string {
	return nativeAmpHeader(version) + "\n\n" +
		nativeAmpCoreFunctions() + "\n\n" +
		nativeAmpHookData(hooks) + "\n\n" +
		"export default function (amp: PluginAPI) {\n" + nativeAmpPluginBody() + "\n}"
}

func nativeAmpHeader(version string) string {
	return `/**
 * Amp Plugin - Agent Skills Hooks
 * Auto-generated by loaf build system
 * @version ` + version + `
 */

import type { PluginAPI } from '@ampcode/plugin';
import { execFile } from 'child_process';
import { promisify } from 'util';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const execFileAsync = promisify(execFile);`
}

func nativeAmpCoreFunctions() string {
	return `// ─────────────────────────────────────────────────────────────────────────────
// Core Hook Functions
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Run a hook via subprocess (loaf check or script execution)
 *
 * Exit codes:
 *   0 = allow (hook passed)
 *   1 = error (hook failed but not blocking)
 *   2 = block (hook rejected the action)
 *
 * @param hookType - 'pre-tool', 'post-tool', or 'session'
 * @param toolName - Name of the tool being invoked
 * @param hookId - Specific hook identifier
 * @param command - Direct command to execute (alternative to script)
 * @param script - Script file to execute
 * @param timeout - Maximum execution time in milliseconds
 * @param failClosed - When true, subprocess errors block the action
 * @returns Hook result with exit code, output, and error information
 */
interface HookResult {
  exitCode: number;
  stdout: string;
  stderr: string;
  error?: string;
}

function serializeHookPayload(toolName: string, toolInput: unknown, rawInput?: unknown): string | undefined {
  const normalizedToolInput =
    toolInput && typeof toolInput === 'object'
      ? toolInput
      : toolInput === undefined
        ? {}
        : { value: toolInput };

  try {
    return JSON.stringify({
      tool: { name: toolName || '' },
      tool_name: toolName || '',
      tool_input: normalizedToolInput,
      input: normalizedToolInput,
      raw: rawInput,
    });
  } catch {
    return undefined;
  }
}

async function runHook(
  hookType: string,
  toolName: string,
  hookId: string,
  command?: string,
  script?: string,
  payload?: string,
  timeout: number = 60000,
  failClosed: boolean = false,
): Promise<HookResult> {
  const env = {
    ...process.env,
    LOAF_HOOK_TYPE: hookType,
    LOAF_HOOK_ID: hookId,
    LOAF_TOOL_NAME: toolName || '',
    LOAF_PLUGIN_DIR: __dirname,
  };

  try {
    // If hook has direct command (e.g., 'loaf check ...'), execute it
    if (command) {
      const child = execFile('bash', ['-c', command], {
        cwd: process.cwd(),
        env,
        encoding: 'utf-8',
        timeout,
      });
      if (payload && child.stdin) {
        child.stdin.write(payload);
        child.stdin.end();
      }

      const result = await new Promise<HookResult>((resolve) => {
        let stdoutStr = '';
        let stderrStr = '';
        child.stdout?.on('data', (data) => stdoutStr += data);
        child.stderr?.on('data', (data) => stderrStr += data);
        child.on('close', (code) => {
          resolve({ exitCode: code ?? 1, stdout: stdoutStr, stderr: stderrStr }); // null means signal-killed; fail closed
        });
        child.on('error', (err) => {
          resolve({ exitCode: failClosed ? 2 : 1, stdout: stdoutStr, stderr: stderrStr || err.message, error: err.message });
        });
      });
      return result;
    }

    // Otherwise run the script file
    if (script) {
      const scriptPath = join(__dirname, 'hooks', script);
      const interpreter = script.endsWith('.py') ? 'python3' : 'bash';
      const child = execFile(interpreter, [scriptPath], {
        cwd: process.cwd(),
        env,
        encoding: 'utf-8',
        timeout,
      });
      if (payload && child.stdin) {
        child.stdin.write(payload);
        child.stdin.end();
      }

      const result = await new Promise<HookResult>((resolve) => {
        let stdoutStr = '';
        let stderrStr = '';
        child.stdout?.on('data', (data) => stdoutStr += data);
        child.stderr?.on('data', (data) => stderrStr += data);
        child.on('close', (code) => {
          resolve({ exitCode: code ?? 1, stdout: stdoutStr, stderr: stderrStr }); // null means signal-killed; fail closed
        });
        child.on('error', (err) => {
          resolve({ exitCode: failClosed ? 2 : 1, stdout: stdoutStr, stderr: stderrStr || err.message, error: err.message });
        });
      });
      return result;
    }

    return { exitCode: 1, stdout: '', stderr: 'No command or script specified' };
  } catch (error: any) {
    return {
      exitCode: failClosed ? 2 : 1,
      stdout: '',
      stderr: error.message,
      error: error.message,
    };
  }
}

/**
 * Check if a tool name matches a pattern
 * Patterns can be:
 *   - Simple wildcard: "Bash*" matches "Bash", "BashFile", etc.
 *   - Union pattern: "Edit|Write" matches either
 *   - Exact match: "Edit" matches only "Edit"
 */
function matchesTool(toolName: string, pattern: string): boolean {
  if (!toolName || !pattern) return false;

  const patterns = pattern.split('|');
  return patterns.some((p) => {
    const trimmed = p.trim();
    if (trimmed.endsWith('*')) {
      return toolName.startsWith(trimmed.slice(0, -1));
    }
    return toolName === trimmed;
  });
}

function matchesIfCondition(toolName: string, toolInput: unknown, ifCondition: string | undefined): boolean {
  if (!ifCondition) return true;

  // Parse pattern like "Bash(gh pr merge:*)" or "Bash(git push:*)"
  // Tool name before '(' and command pattern inside parentheses
  const match = ifCondition.match(/^(\w+)\(([^)]+)\)$/);
  if (!match) return true;

  const [, expectedTool, commandPattern] = match;
  if (toolName !== expectedTool) return false;

  const input = toolInput as Record<string, unknown> | undefined;
  const command = (input?.command || input?.file_path) as string | undefined;
  if (!command) return false;

  // Handle glob patterns with :* suffix (e.g., "git commit:*" means "starts with git commit")
  // The :* format treats everything before : as a literal prefix, * matches anything after
  if (commandPattern.endsWith(':')) {
    // Pattern like "git commit:" - match commands starting with this prefix
    const prefix = commandPattern.slice(0, -1);
    return command.startsWith(prefix);
  }

  if (commandPattern.endsWith(':*')) {
    // Pattern like "git commit:*" - match commands starting with "git commit"
    const prefix = commandPattern.slice(0, -2);
    return command.startsWith(prefix);
  }

  // For other patterns, convert glob to regex
  // Escape regex special characters then convert * to .* and ? to .
  let regexPattern = commandPattern
    .replace(/[.+^$"{}()|[\]\\]/g, '\\$&')
    .replace(/\*/g, '.*')
    .replace(/\?/g, '.');

  const regex = new RegExp('^' + regexPattern + '$');
  return regex.test(command);
}
`
}

func nativeAmpHookData(hooks []nativeBuildHook) string {
	preTool := nativeAmpGroupHooksByMatcher(filterNativeBuildHooks(hooks, "pre-tool"))
	postTool := nativeAmpGroupHooksByMatcher(filterNativeBuildHooks(hooks, "post-tool"))
	session := nativeAmpGroupSessionHooks(filterNativeBuildHooks(hooks, "session"))
	return `// ─────────────────────────────────────────────────────────────────────────────
// Hook Data
// ─────────────────────────────────────────────────────────────────────────────

interface HookEntry {
  id: string;
  command?: string;
  script?: string;
  timeout: number;
  failClosed: boolean;
  if?: string;
}

const preToolHooks: Record<string, HookEntry[]> = ` + marshalNativeAmpHookMap(preTool) + `;

const postToolHooks: Record<string, HookEntry[]> = ` + marshalNativeAmpHookMap(postTool) + `;

const sessionHooks: Record<string, HookEntry[]> = ` + marshalNativeAmpHookMap(session) + `;`
}

func nativeAmpPluginBody() string {
	body := `  amp.on('session.start', async () => {
    for (const hookList of Object.values(sessionHooks)) {
      for (const hook of hookList) {
        const result = await runHook('session', 'session', hook.id, hook.command, hook.script, undefined, hook.timeout, hook.failClosed);
        if (result.exitCode !== 0) {
          console.warn(%%BT%%[loaf] Session hook ${hook.id} error (exit ${result.exitCode}): ${result.stderr}%%BT%%);
        }
      }
    }
  });

  amp.on('tool.call', async (event) => {
      const toolName = event?.tool;
      const toolInput = event?.input ?? event?.arguments ?? {};
      if (!toolName) return;

      const hookPayload = serializeHookPayload(toolName, toolInput, event);

      for (const [matcher, hookList] of Object.entries(preToolHooks)) {
        if (matchesTool(toolName, matcher)) {
          for (const hook of hookList) {
            if (!matchesIfCondition(toolName, toolInput, hook.if)) continue;
            const result = await runHook('pre-tool', toolName, hook.id, hook.command, hook.script, hookPayload, hook.timeout, hook.failClosed);

            // Exit code 2 = block the action
            if (result.exitCode === 2) {
              return { action: 'reject-and-continue', message: result.stderr };
            }

            // Log errors for debugging
            if (result.exitCode === 1) {
              console.warn(%%BT%%[loaf] Hook ${hook.id} error: ${result.stderr}%%BT%%);
            }
          }
        }
      }
    });

  amp.on('tool.result', async (event) => {
      const toolName = event?.tool;
      const toolInput = event?.input ?? event?.arguments ?? {};
      if (!toolName) return;

      const hookPayload = serializeHookPayload(toolName, toolInput, event);

      for (const [matcher, hookList] of Object.entries(postToolHooks)) {
        if (matchesTool(toolName, matcher)) {
          for (const hook of hookList) {
            if (!matchesIfCondition(toolName, toolInput, hook.if)) continue;
            const result = await runHook('post-tool', toolName, hook.id, hook.command, hook.script, hookPayload, hook.timeout, hook.failClosed);

            if (result.exitCode !== 0) {
              console.warn(%%BT%%[loaf] Post-hook ${hook.id} error (exit ${result.exitCode}): ${result.stderr}%%BT%%);
            }
          }
        }
      }
    });`
	return strings.ReplaceAll(body, "%%BT%%", "`")
}

func filterNativeBuildHooks(hooks []nativeBuildHook, hookType string) []nativeBuildHook {
	var filtered []nativeBuildHook
	for _, hook := range hooks {
		if hook.section == hookType && hook.typeName != "prompt" {
			filtered = append(filtered, hook)
		}
	}
	return filtered
}

func nativeAmpGroupHooksByMatcher(hooks []nativeBuildHook) []nativeAmpHookGroup {
	var grouped []nativeAmpHookGroup
	for _, hook := range hooks {
		matcher := hook.matcher
		if matcher == "" {
			matcher = "Edit|Write"
		}
		grouped = appendNativeAmpHookGroup(grouped, matcher, nativeAmpHookEntryFor(hook))
	}
	return grouped
}

func nativeAmpGroupSessionHooks(hooks []nativeBuildHook) []nativeAmpHookGroup {
	var grouped []nativeAmpHookGroup
	for _, hook := range hooks {
		event := strings.ToLower(strings.Join(strings.Fields(hook.event), ""))
		if event == "" {
			continue
		}
		grouped = appendNativeAmpHookGroup(grouped, event, nativeAmpHookEntryFor(hook))
	}
	return grouped
}

func appendNativeAmpHookGroup(groups []nativeAmpHookGroup, name string, entry nativeAmpHookEntry) []nativeAmpHookGroup {
	for i := range groups {
		if groups[i].name == name {
			groups[i].entries = append(groups[i].entries, entry)
			return groups
		}
	}
	return append(groups, nativeAmpHookGroup{name: name, entries: []nativeAmpHookEntry{entry}})
}

func nativeAmpHookEntryFor(hook nativeBuildHook) nativeAmpHookEntry {
	entry := nativeAmpHookEntry{
		ID:         hook.id,
		Command:    hook.command,
		Timeout:    hook.timeout,
		FailClosed: hook.failClosed,
		If:         hook.ifCondition,
	}
	if entry.Timeout == 0 {
		entry.Timeout = 60000
	}
	if hook.instruction != "" {
		entry.Command = `cat "$LOAF_PLUGIN_DIR/hooks/` + hook.instruction + `"`
	}
	if entry.Command == "" && hook.script != "" {
		entry.Script = nativeBuildScriptFilename(hook.script)
	}
	if entry.Command == "" && entry.Script == "" && nativeBuildRuntimePluginCheckHooks[hook.id] {
		entry.Command = "loaf check --hook " + hook.id
	}
	return entry
}

var nativeBuildRuntimePluginCheckHooks = map[string]bool{
	"check-" + "sec" + "rets": true,
	"validate-push":           true,
	"validate-commit":         true,
	"workflow-pre-pr":         true,
	"security-audit":          true,
}

func marshalNativeAmpHookMap(groups []nativeAmpHookGroup) string {
	if len(groups) == 0 {
		return "{}"
	}
	var out strings.Builder
	out.WriteString("{\n")
	for i, group := range groups {
		key, err := json.Marshal(group.name)
		if err != nil {
			panic(err)
		}
		entries, err := json.MarshalIndent(group.entries, "  ", "  ")
		if err != nil {
			panic(err)
		}
		out.WriteString("  ")
		out.Write(key)
		out.WriteString(": ")
		out.Write(entries)
		if i < len(groups)-1 {
			out.WriteByte(',')
		}
		out.WriteByte('\n')
	}
	out.WriteByte('}')
	return out.String()
}

func nativeBuildScriptFilename(scriptPath string) string {
	parts := strings.Split(scriptPath, "/")
	if len(parts) <= 2 {
		return scriptPath
	}
	return strings.Join(parts[len(parts)-2:], "/")
}

func readNativeBuildHooks(path string) ([]nativeBuildHook, error) {
	body, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var hooks []nativeBuildHook
	var section string
	var current *nativeBuildHook
	for _, line := range strings.Split(string(body), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		if strings.HasPrefix(line, "  ") && !strings.HasPrefix(line, "    ") && strings.HasSuffix(trimmed, ":") {
			if current != nil {
				hooks = append(hooks, *current)
				current = nil
			}
			section = strings.TrimSuffix(trimmed, ":")
			continue
		}
		if section == "" {
			continue
		}
		if strings.HasPrefix(trimmed, "- id:") {
			if current != nil {
				hooks = append(hooks, *current)
			}
			current = &nativeBuildHook{section: section}
			current.id = unquoteNativeBuildYAML(strings.TrimSpace(strings.TrimPrefix(trimmed, "- id:")))
			continue
		}
		if current == nil || !strings.Contains(trimmed, ":") {
			continue
		}
		key, value, _ := strings.Cut(trimmed, ":")
		value = unquoteNativeBuildYAML(strings.TrimSpace(value))
		switch key {
		case "matcher":
			current.matcher = value
		case "command":
			current.command = value
		case "script":
			current.script = value
		case "instruction":
			current.instruction = value
		case "prompt":
			current.prompt = value
		case "event":
			current.event = value
		case "type":
			current.typeName = value
		case "timeout":
			if parsed, err := strconv.Atoi(value); err == nil {
				current.timeout = parsed
			}
		case "failClosed":
			current.failClosed = value == "true"
		case "blocking":
			current.blocking = value == "true"
		case "if":
			current.ifCondition = value
		case "description":
			current.description = value
		}
	}
	if current != nil {
		hooks = append(hooks, *current)
	}
	return hooks, nil
}
