package cli

import (
	"bytes"
	"errors"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestScopedUpgradeRejectsInteractiveTargetSelection(t *testing.T) {
	for _, flag := range []string{"-i", "--interactive"} {
		if _, err := parseUpgradeArgs([]string{"--select", "skills/skill:foundations", flag}); err == nil || !strings.Contains(err.Error(), "cannot be combined") {
			t.Fatalf("--select %s error = %v, want conflicting selection modes rejected", flag, err)
		}
	}
}

type forbiddenScopedClaudeCLI struct{ t *testing.T }

func (c forbiddenScopedClaudeCLI) run(args ...string) (string, error) {
	c.t.Fatalf("scoped upgrade consulted unselected Claude plugin state: %v", args)
	return "", nil
}

func TestScopedUpgradeDoesNotConsultUnselectedClaude(t *testing.T) {
	for _, dryRun := range []bool{true, false} {
		t.Run(map[bool]string{true: "preview", false: "apply"}[dryRun], func(t *testing.T) {
			root, _ := setupScopedUpgradeFixture(t)
			writeClaudeMarketplaceManifest(t, root)
			claudePath := filepath.Join(root, "bin", "claude")
			writeInstallFile(t, claudePath, "#!/bin/sh\nexit 1\n")
			if err := os.Chmod(claudePath, 0o755); err != nil {
				t.Fatal(err)
			}
			if !installCommandExists("claude") {
				t.Fatal("fixture did not expose claude on PATH")
			}
			args := []string{"upgrade", "--select", "skills/skill:foundations"}
			if dryRun {
				args = append(args, "--dry-run", "--json")
			}
			err := (Runner{Stdout: io.Discard, WorkingDir: root, Executable: distributionFixtureExecutable(root), ClaudePluginCLI: forbiddenScopedClaudeCLI{t}}).Run(args)
			if err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestScopedUpgradeMigratesJavaScriptAdapterPredecessors(t *testing.T) {
	ampHeader := "/**\n * Amp Plugin - Agent Skills Hooks\n * Auto-generated by loaf build system\n */\n"
	openCodeHeader := "/**\n * OpenCode Plugin - Agent Skills Hooks\n * Auto-generated by loaf build system\n */\n"
	type predecessorKind string
	const (
		predecessorManaged    predecessorKind = "managed"
		predecessorModified   predecessorKind = "modified"
		predecessorForeign    predecessorKind = "foreign"
		predecessorUnrecorded predecessorKind = "unrecorded-symlink"
	)
	for _, tc := range []struct {
		name         string
		target       string
		selectID     string
		sourcePath   string
		destination  string
		legacyID     string
		legacySource string
		legacyDest   string
		header       string
		kind         predecessorKind
	}{
		{name: "amp-hook-managed", target: "amp", selectID: ampHookPluginArtifactID, sourcePath: ".amp/plugins/loaf.js", destination: "plugins/loaf.js", legacyID: ampHookPluginPredecessorID, legacySource: ".amp/plugins/loaf.ts", legacyDest: "plugins/loaf.ts", header: ampHeader, kind: predecessorManaged},
		{name: "amp-hook-modified", target: "amp", selectID: ampHookPluginArtifactID, sourcePath: ".amp/plugins/loaf.js", destination: "plugins/loaf.js", legacyID: ampHookPluginPredecessorID, legacySource: ".amp/plugins/loaf.ts", legacyDest: "plugins/loaf.ts", header: ampHeader, kind: predecessorModified},
		{name: "amp-hook-foreign", target: "amp", selectID: ampHookPluginArtifactID, sourcePath: ".amp/plugins/loaf.js", destination: "plugins/loaf.js", legacyID: ampHookPluginPredecessorID, legacySource: ".amp/plugins/loaf.ts", legacyDest: "plugins/loaf.ts", header: ampHeader, kind: predecessorForeign},
		{name: "amp-hook-unrecorded-symlink", target: "amp", selectID: ampHookPluginArtifactID, sourcePath: ".amp/plugins/loaf.js", destination: "plugins/loaf.js", legacyID: ampHookPluginPredecessorID, legacySource: ".amp/plugins/loaf.ts", legacyDest: "plugins/loaf.ts", header: ampHeader, kind: predecessorUnrecorded},
		{name: "opencode-managed", target: "opencode", selectID: openCodeHookPluginArtifactID, sourcePath: "plugins/hooks.js", destination: "plugins/hooks.js", legacyID: openCodeHookPluginPredecessorID, legacySource: "plugins/hooks.ts", legacyDest: "plugins/hooks.ts", header: openCodeHeader, kind: predecessorManaged},
		{name: "opencode-modified", target: "opencode", selectID: openCodeHookPluginArtifactID, sourcePath: "plugins/hooks.js", destination: "plugins/hooks.js", legacyID: openCodeHookPluginPredecessorID, legacySource: "plugins/hooks.ts", legacyDest: "plugins/hooks.ts", header: openCodeHeader, kind: predecessorModified},
		{name: "opencode-foreign", target: "opencode", selectID: openCodeHookPluginArtifactID, sourcePath: "plugins/hooks.js", destination: "plugins/hooks.js", legacyID: openCodeHookPluginPredecessorID, legacySource: "plugins/hooks.ts", legacyDest: "plugins/hooks.ts", header: openCodeHeader, kind: predecessorForeign},
		{name: "opencode-unrecorded-symlink", target: "opencode", selectID: openCodeHookPluginArtifactID, sourcePath: "plugins/hooks.js", destination: "plugins/hooks.js", legacyID: openCodeHookPluginPredecessorID, legacySource: "plugins/hooks.ts", legacyDest: "plugins/hooks.ts", header: openCodeHeader, kind: predecessorUnrecorded},
	} {
		t.Run(tc.name, func(t *testing.T) {
			root, home := setupScopedUpgradeFixture(t)
			dist := filepath.Join(root, "dist", tc.target)
			config := filepath.Join(home, ".config", tc.target)
			if tc.target == "amp" {
				writeInstallFile(t, filepath.Join(config, loafInstallMarkerFile), "0.5.0\n")
			}
			desired := "export const successor = 2;\n"
			if tc.header != "" {
				desired = tc.header + desired
			}
			legacyBody := "export const predecessor = 1;\n"
			if tc.header != "" {
				legacyBody = tc.header + legacyBody
			}
			writeInstallFile(t, filepath.Join(dist, filepath.FromSlash(tc.sourcePath)), desired)
			writeTestTargetAdapterManifest(t, dist, tc.target, []map[string]string{{
				"id": tc.selectID, "kind": "plugin", "source_path": tc.sourcePath, "destination": tc.destination, "sha256": sha256Hex(desired),
			}})
			legacyPath := filepath.Join(config, filepath.FromSlash(tc.legacyDest))
			successorPath := filepath.Join(config, filepath.FromSlash(tc.destination))
			if err := os.Remove(successorPath); err != nil && !os.IsNotExist(err) {
				t.Fatalf("Remove existing successor: %v", err)
			}
			assertInstallPathMissing(t, successorPath)
			switch tc.kind {
			case predecessorManaged, predecessorModified:
				writeInstallFile(t, legacyPath, legacyBody)
				legacyMode := uint32(0o644)
				if err := writeTargetAdapterManifest(filepath.Join(config, targetInstallManifestFile), targetAdapterManifest{
					Version: 1, Target: tc.target, PackageVersion: "0.5.0", CapabilityContractVersion: 3,
					Adapters: []string{tc.target + "-test-adapter-v1"},
					Artifacts: []targetAdapterArtifact{{
						ID: tc.legacyID, Kind: "plugin", SourcePath: tc.legacySource,
						Destination: tc.legacyDest, SHA256: sha256Hex(legacyBody), Mode: &legacyMode,
					}},
				}); err != nil {
					t.Fatalf("write predecessor ownership: %v", err)
				}
				if tc.kind == predecessorModified {
					writeInstallFile(t, legacyPath, legacyBody+"local-edit\n")
					legacyBody += "local-edit\n"
				}
			case predecessorForeign:
				writeInstallFile(t, legacyPath, "export const foreign = true;\n")
				legacyBody = "export const foreign = true;\n"
			case predecessorUnrecorded:
				mkdirAll(t, filepath.Dir(legacyPath))
				if err := os.Symlink(filepath.Join(root, "missing-legacy.ts"), legacyPath); err != nil {
					t.Fatalf("Symlink unrecorded predecessor: %v", err)
				}
			}
			args := []string{"upgrade", "--select", tc.target + "/" + tc.selectID}
			var stdout bytes.Buffer
			err := (Runner{Stdout: &stdout, WorkingDir: root, Executable: distributionFixtureExecutable(root)}).Run(args)
			if tc.kind == predecessorManaged {
				if err != nil {
					t.Fatalf("scoped successor upgrade error = %v\n%s", err, stdout.String())
				}
				assertInstallFile(t, successorPath, desired)
				assertInstallPathMissing(t, legacyPath)
				installed, readErr := readTargetAdapterManifest(filepath.Join(config, targetInstallManifestFile))
				if readErr != nil {
					t.Fatalf("read installed ownership: %v", readErr)
				}
				if _, ok := targetAdapterArtifactsByID(installed.Artifacts)[tc.legacyID]; ok {
					t.Fatalf("installed artifacts = %#v, want predecessor retired", installed.Artifacts)
				}
				if _, ok := targetAdapterArtifactsByID(installed.Artifacts)[tc.selectID]; !ok {
					t.Fatalf("installed artifacts = %#v, want successor owned", installed.Artifacts)
				}
				return
			}
			if err == nil {
				t.Fatalf("scoped successor upgrade succeeded, want conflict\n%s", stdout.String())
			}
			combined := err.Error() + stdout.String()
			if tc.kind == predecessorUnrecorded {
				if !strings.Contains(combined, "symlink") {
					t.Fatalf("unrecorded symlink error = %v\n%s, want symlink conflict", err, stdout.String())
				}
				info, statErr := os.Lstat(legacyPath)
				if statErr != nil || info.Mode()&os.ModeSymlink == 0 {
					t.Fatalf("unrecorded predecessor Lstat = %v info=%v, want preserved symlink", statErr, info)
				}
			} else {
				if !strings.Contains(combined, "modified") && !strings.Contains(combined, "not proven Loaf-owned") && !strings.Contains(combined, "not managed by Loaf") && !strings.Contains(combined, "selected conflict") {
					t.Fatalf("scoped predecessor conflict = %v\n%s", err, stdout.String())
				}
				assertInstallFile(t, legacyPath, legacyBody)
			}
			assertInstallPathMissing(t, successorPath)
		})
	}
}

func TestScopedUpgradePreservesLateOwnedAbsentPredecessor(t *testing.T) {
	root, home := setupScopedUpgradeFixture(t)
	dist := filepath.Join(root, "dist", "amp")
	config := filepath.Join(home, ".config", "amp")
	desired := "/**\n * Amp Plugin - Agent Skills Hooks\n * Auto-generated by loaf build system\n */\nexport const successor = 2;\n"
	writeInstallFile(t, filepath.Join(config, loafInstallMarkerFile), "0.5.0\n")
	writeInstallFile(t, filepath.Join(dist, ".amp", "plugins", "loaf.js"), desired)
	writeTestTargetAdapterManifest(t, dist, "amp", []map[string]string{{
		"id": ampHookPluginArtifactID, "kind": "plugin", "source_path": ".amp/plugins/loaf.js", "destination": "plugins/loaf.js", "sha256": sha256Hex(desired),
	}})
	legacyPath := filepath.Join(config, "plugins", "loaf.ts")
	successorPath := filepath.Join(config, "plugins", "loaf.js")
	if err := os.Remove(successorPath); err != nil && !os.IsNotExist(err) {
		t.Fatalf("Remove existing successor: %v", err)
	}
	assertInstallPathMissing(t, successorPath)
	assertInstallPathMissing(t, legacyPath)
	legacyMode := uint32(0o644)
	if err := writeTargetAdapterManifest(filepath.Join(config, targetInstallManifestFile), targetAdapterManifest{
		Version: 1, Target: "amp", PackageVersion: "0.5.0", CapabilityContractVersion: 3,
		Adapters: []string{"amp-test-adapter-v1"},
		Artifacts: []targetAdapterArtifact{{
			ID: ampHookPluginPredecessorID, Kind: "plugin", SourcePath: ".amp/plugins/loaf.ts",
			Destination: "plugins/loaf.ts", SHA256: sha256Hex("retired\n"), Mode: &legacyMode,
		}},
	}); err != nil {
		t.Fatalf("write absent predecessor ownership: %v", err)
	}
	t.Cleanup(func() { scopedApplyTestFault = nil })
	scopedApplyTestFault = func(phase string) error {
		if phase != "amp-adapters" {
			return nil
		}
		writeInstallFile(t, legacyPath, "late leftover\n")
		return errors.New("injected late predecessor")
	}
	var stdout bytes.Buffer
	err := (Runner{Stdout: &stdout, WorkingDir: root, Executable: distributionFixtureExecutable(root)}).Run([]string{"upgrade", "--select", "amp/" + ampHookPluginArtifactID})
	if err == nil {
		t.Fatalf("scoped late predecessor upgrade succeeded, want conflict\n%s", stdout.String())
	}
	assertInstallFile(t, legacyPath, "late leftover\n")
	assertInstallPathMissing(t, successorPath)
	installed, readErr := readTargetAdapterManifest(filepath.Join(config, targetInstallManifestFile))
	if readErr != nil {
		t.Fatalf("read installed ownership: %v", readErr)
	}
	if _, ok := targetAdapterArtifactsByID(installed.Artifacts)[ampHookPluginArtifactID]; ok {
		t.Fatalf("installed artifacts = %#v, want successor unpublished", installed.Artifacts)
	}
	if _, ok := targetAdapterArtifactsByID(installed.Artifacts)[ampHookPluginPredecessorID]; !ok {
		t.Fatalf("installed artifacts = %#v, want predecessor ownership unchanged", installed.Artifacts)
	}
}

func TestScopedUpgradePreservesRecreatedPresentPredecessor(t *testing.T) {
	for _, tc := range []struct {
		name   string
		inject string
	}{
		{name: "file", inject: "file"},
		{name: "dangling-symlink", inject: "symlink"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			root, home := setupScopedUpgradeFixture(t)
			dist := filepath.Join(root, "dist", "amp")
			config := filepath.Join(home, ".config", "amp")
			oldPlugin := "/**\n * Amp Plugin - Agent Skills Hooks\n * Auto-generated by loaf build system\n */\nold\n"
			desired := "/**\n * Amp Plugin - Agent Skills Hooks\n * Auto-generated by loaf build system\n */\nexport const successor = 2;\n"
			writeInstallFile(t, filepath.Join(config, loafInstallMarkerFile), "0.5.0\n")
			writeInstallFile(t, filepath.Join(dist, ".amp", "plugins", "loaf.js"), desired)
			writeTestTargetAdapterManifest(t, dist, "amp", []map[string]string{{
				"id": ampHookPluginArtifactID, "kind": "plugin", "source_path": ".amp/plugins/loaf.js", "destination": "plugins/loaf.js", "sha256": sha256Hex(desired),
			}})
			legacyPath := filepath.Join(config, "plugins", "loaf.ts")
			successorPath := filepath.Join(config, "plugins", "loaf.js")
			if err := os.Remove(successorPath); err != nil && !os.IsNotExist(err) {
				t.Fatalf("Remove existing successor: %v", err)
			}
			writeInstallFile(t, legacyPath, oldPlugin)
			legacyMode := uint32(0o644)
			if err := writeTargetAdapterManifest(filepath.Join(config, targetInstallManifestFile), targetAdapterManifest{
				Version: 1, Target: "amp", PackageVersion: "0.5.0", CapabilityContractVersion: 3,
				Adapters: []string{"amp-test-adapter-v1"},
				Artifacts: []targetAdapterArtifact{{
					ID: ampHookPluginPredecessorID, Kind: "plugin", SourcePath: ".amp/plugins/loaf.ts",
					Destination: "plugins/loaf.ts", SHA256: sha256Hex(oldPlugin), Mode: &legacyMode,
				}},
			}); err != nil {
				t.Fatalf("write predecessor ownership: %v", err)
			}
			t.Cleanup(func() { scopedApplyTestFault = nil })
			scopedApplyTestFault = func(phase string) error {
				if phase != "amp-adapters" {
					return nil
				}
				switch tc.inject {
				case "file":
					writeInstallFile(t, legacyPath, "late leftover\n")
				case "symlink":
					if err := os.Remove(legacyPath); err != nil && !os.IsNotExist(err) {
						t.Fatalf("Remove retired predecessor: %v", err)
					}
					if err := os.Symlink(filepath.Join(root, "missing-legacy.ts"), legacyPath); err != nil {
						t.Fatalf("Symlink recreated predecessor: %v", err)
					}
				}
				return errors.New("injected recreated predecessor")
			}
			var stdout bytes.Buffer
			err := (Runner{Stdout: &stdout, WorkingDir: root, Executable: distributionFixtureExecutable(root)}).Run([]string{"upgrade", "--select", "amp/" + ampHookPluginArtifactID})
			if err == nil {
				t.Fatalf("scoped recreated predecessor upgrade succeeded, want conflict\n%s", stdout.String())
			}
			if tc.inject == "file" {
				assertInstallFile(t, legacyPath, "late leftover\n")
			} else {
				info, statErr := os.Lstat(legacyPath)
				if statErr != nil || info.Mode()&os.ModeSymlink == 0 {
					t.Fatalf("recreated predecessor Lstat = %v info=%v, want preserved dangling symlink", statErr, info)
				}
			}
			assertInstallPathMissing(t, successorPath)
			installed, readErr := readTargetAdapterManifest(filepath.Join(config, targetInstallManifestFile))
			if readErr != nil {
				t.Fatalf("read installed ownership: %v", readErr)
			}
			if _, ok := targetAdapterArtifactsByID(installed.Artifacts)[ampHookPluginArtifactID]; ok {
				t.Fatalf("installed artifacts = %#v, want successor unpublished", installed.Artifacts)
			}
			if _, ok := targetAdapterArtifactsByID(installed.Artifacts)[ampHookPluginPredecessorID]; !ok {
				t.Fatalf("installed artifacts = %#v, want predecessor ownership unchanged", installed.Artifacts)
			}
		})
	}
}

func TestScopedUpgradePreservesUnmanifestedAmpModesPredecessor(t *testing.T) {
	root, home := setupScopedUpgradeFixture(t)
	dist := filepath.Join(root, "dist", "amp")
	config := filepath.Join(home, ".config", "amp")
	plugins := filepath.Join(config, "plugins")
	hookID := ampHookPluginArtifactID
	predecessor := testAmpModesPredecessor(t)
	writeDistribution := func(hooks string) {
		t.Helper()
		writeInstallFile(t, filepath.Join(dist, ".amp", "plugins", "loaf.js"), hooks)
		writeTestTargetAdapterManifest(t, dist, "amp", []map[string]string{
			{"id": hookID, "kind": "plugin", "source_path": ".amp/plugins/loaf.js", "destination": "plugins/loaf.js", "sha256": sha256Hex(hooks)},
		})
	}
	writeDistribution("export const hooks = 1;\n")
	if err := syncTargetAdapterManifest(targetInstallOptions{Target: "amp", DistDir: dist, ConfigDir: config, HomeDir: home, Version: "0.5.0"}); err != nil {
		t.Fatal(err)
	}
	writeInstallFile(t, filepath.Join(config, loafInstallMarkerFile), "0.5.0\n")
	before, err := readTargetAdapterManifest(filepath.Join(config, targetInstallManifestFile))
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := targetAdapterArtifactsByID(before.Artifacts)[ampModesPluginArtifactID]; ok {
		t.Fatalf("installed Amp artifacts = %#v, want no loaf-modes.ts row", before.Artifacts)
	}
	writeInstallFile(t, filepath.Join(plugins, "loaf-modes.ts"), predecessor)
	writeDistribution("export const hooks = 2;\n")
	preview := runInstallCapture(t, root, "upgrade", "--select", "amp/"+hookID, "--dry-run", "--json")
	if strings.Contains(preview, ampModesPluginArtifactID) || strings.Contains(preview, "loaf-modes") {
		t.Fatalf("selected loaf.js preview claimed modes retirement:\n%s", preview)
	}
	if got := findScopedTargetArtifact(t, parseInstallPlanJSON(t, preview), "amp", hookID); got.Action != planActionUpdate {
		t.Fatalf("selected loaf.js preview action = %#v, want update", got)
	}
	runInstallCapture(t, root, "upgrade", "--select", "amp/"+hookID)
	assertInstallFile(t, filepath.Join(plugins, "loaf.js"), "export const hooks = 2;\n")
	assertInstallFile(t, filepath.Join(plugins, "loaf-modes.ts"), predecessor)
	assertInstallFile(t, filepath.Join(config, loafInstallMarkerFile), "0.5.0\n")
	after, err := readTargetAdapterManifest(filepath.Join(config, targetInstallManifestFile))
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := targetAdapterArtifactsByID(after.Artifacts)[ampModesPluginArtifactID]; ok {
		t.Fatalf("scoped loaf.js upgrade added modes row: %#v", after.Artifacts)
	}
}

func TestScopedUpgradeRejectsLegacyWholeTargetBeforeWrites(t *testing.T) {
	for _, dryRun := range []bool{true, false} {
		t.Run(map[bool]string{true: "preview", false: "apply"}[dryRun], func(t *testing.T) {
			root, home := setupScopedUpgradeFixture(t)
			if err := os.Remove(filepath.Join(root, "dist", "opencode", targetBuildManifestFile)); err != nil {
				t.Fatal(err)
			}
			foreign := filepath.Join(home, ".config", "opencode", "foreign.txt")
			writeInstallFile(t, foreign, "user-owned\n")
			if err := os.Chmod(foreign, 0o640); err != nil {
				t.Fatal(err)
			}
			before, err := os.Stat(foreign)
			if err != nil {
				t.Fatal(err)
			}
			surfaces := hashScopedSurfaces(t, home)
			args := []string{"upgrade", "--select", "opencode/hooks", "--select", "skills/skill:foundations"}
			if dryRun {
				args = append(args, "--dry-run", "--json")
			}
			var output bytes.Buffer
			err = (Runner{Stdout: &output, WorkingDir: root, Executable: distributionFixtureExecutable(root)}).Run(args)
			if err == nil || !strings.Contains(err.Error()+output.String(), "legacy whole-target") {
				t.Errorf("error = %v, output = %s, want legacy whole-target selection rejected", err, output.String())
			}
			after, err := os.Stat(foreign)
			if err != nil {
				t.Fatal(err)
			}
			if !os.SameFile(before, after) || before.Mode() != after.Mode() || hashScopedSurfaces(t, home) != surfaces {
				t.Fatal("rejected legacy selection changed harness or skill surfaces")
			}
		})
	}
}

func TestUpgradeTargetPlanHonorsExplicitFilter(t *testing.T) {
	root, _ := setupScopedUpgradeFixture(t)
	writeClaudeMarketplaceManifest(t, root)
	r := Runner{ClaudePluginCLI: forbiddenScopedClaudeCLI{t}}
	options, err := parseUpgradeArgs([]string{"--to", "cursor", "--dry-run"})
	if err != nil {
		t.Fatal(err)
	}
	plan, err := r.buildInstallDryRunPlan(options.installPlanOptions(), root, root, "0.6.0", filepath.Join(root, "dist"), detectInstallTools(), true, false, &projectPartPlan{InScope: false})
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Targets) != 1 || plan.Targets[0].Target != "cursor" {
		t.Fatalf("filtered target plan = %#v, want only Cursor", plan.Targets)
	}
}

func TestUpgradeExplicitClaudeRequiresCLI(t *testing.T) {
	options, err := parseUpgradeArgs([]string{"--to", "claude-code"})
	if err != nil {
		t.Fatal(err)
	}
	_, _, err = (Runner{}).selectUpgradeTargets(options, nil, false, io.Discard)
	if err == nil || !strings.Contains(err.Error(), "not on PATH") {
		t.Fatalf("error = %v, want missing Claude CLI guidance", err)
	}
}

func TestUpgradePlanPreservesResolvedEmptyTargetSelection(t *testing.T) {
	root, _ := setupScopedUpgradeFixture(t)
	r := Runner{ClaudePluginCLI: forbiddenScopedClaudeCLI{t}}
	options := installOptions{upgrade: true, resolvedUpgradeTargets: []string{}}
	plan, err := r.buildInstallDryRunPlan(options, root, root, "0.6.0", filepath.Join(root, "dist"), detectInstallTools(), true, false, &projectPartPlan{InScope: false})
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Targets) != 0 {
		t.Fatalf("empty target selection expanded to %#v", plan.Targets)
	}
}

func TestUpgradeFollowUpPreservesResolvedTargetSelection(t *testing.T) {
	for _, test := range []struct {
		name    string
		targets []string
		want    string
	}{
		{name: "subset", targets: []string{"cursor"}, want: "loaf upgrade --to cursor"},
		{name: "including Claude", targets: []string{"cursor", "claude-code"}, want: "loaf upgrade --to cursor,claude-code"},
		{name: "none", targets: []string{}, want: ""},
	} {
		t.Run(test.name, func(t *testing.T) {
			options := installOptions{upgrade: true, command: "upgrade", resolvedUpgradeTargets: test.targets}
			plan := installDryRunPlan{Skills: []artifactPlanDecision{{Kind: "skill", ID: "skill:foundations", Action: planActionUpdate}}}
			commands := installPlanFollowUpCommands(options, plan, false)
			if test.want == "" {
				if len(commands) != 0 {
					t.Fatalf("empty selection follow-up = %q, want no unfiltered apply suggestion", commands)
				}
			} else if len(commands) != 1 || commands[0] != test.want {
				t.Fatalf("follow-up = %q, want %q", commands, test.want)
			}
		})
	}
}

func TestUpgradeInteractiveDryRunAdvertisesOnlySelectedTargets(t *testing.T) {
	for _, selection := range []string{"cursor", "none"} {
		t.Run(selection, func(t *testing.T) {
			root, _ := setupScopedUpgradeFixture(t)
			var output bytes.Buffer
			err := (Runner{Stdout: &output, Stdin: strings.NewReader(selection + "\n"), WorkingDir: root, Executable: distributionFixtureExecutable(root)}).Run([]string{"upgrade", "-i", "--dry-run"})
			if err != nil {
				t.Fatalf("interactive preview: %v\n%s", err, output.String())
			}
			if selection == "none" {
				if strings.Contains(output.String(), "Apply with") {
					t.Fatalf("empty selection advertised an apply command:\n%s", output.String())
				}
			} else if !strings.Contains(output.String(), "loaf upgrade --to cursor") {
				t.Fatalf("preview lost selected target in follow-up:\n%s", output.String())
			}
		})
	}
}
