package main

import (
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"
)

func TestSessionModelConvergenceContentGuards(t *testing.T) {
	root := repoRoot(t)

	searchRoots := []string{
		"content",
		"dist",
		filepath.ToSlash(filepath.Join("plugins", "loaf")),
		".agents/AGENTS.md",
		".claude/CLAUDE.md",
	}
	forbidden := []string{
		"loaf session housekeeping",
		".agents/transcripts/",
		"Transcript Archival",
		"MANDATORY: Create session file",
		"DO NOT PROCEED WITHOUT A SESSION FILE",
		"transcripts:",
	}

	var failures []string
	for _, rel := range searchRoots {
		path := filepath.Join(root, filepath.FromSlash(rel))
		failures = append(failures, forbiddenContentMatches(t, path, forbidden)...)
	}
	sort.Strings(failures)
	if len(failures) > 0 {
		t.Fatalf("session model convergence forbidden content remains:\n%s", strings.Join(failures, "\n"))
	}
}

// TestJournalFirstContentNamespaceConverged is the SPEC-056 Track 4 grep gate:
// zero `loaf session` references across skills, agents, hooks, templates, and
// docs source. The `loaf session` namespace was deleted with no alias, so any
// surviving reference resolves to "unknown command." loaf-reference/SKILL.md is
// generated by build:cli-ref from the engine, which no longer registers the
// namespace, so it is in scope too. The engine cleanup allowlist in
// internal/cli/install_target.go intentionally retains legacy `loaf session`
// signatures to scrub old installs and is out of scope here.
func TestJournalFirstContentNamespaceConverged(t *testing.T) {
	root := repoRoot(t)
	forbidden := []string{"loaf session"}

	var failures []string
	for _, rel := range []string{"content", filepath.FromSlash("config/targets.yaml"), filepath.FromSlash("config/hooks.yaml")} {
		path := filepath.Join(root, rel)
		failures = append(failures, forbiddenContentMatches(t, path, forbidden)...)
	}
	sort.Strings(failures)
	if len(failures) > 0 {
		t.Fatalf("journal-first content namespace not converged (`loaf session` deleted):\n%s", strings.Join(failures, "\n"))
	}
}

// TestJournalFirstHookSurfacesConverged asserts the hook definition and
// generated hook artifacts carry no session-entity commands (SPEC-056 Track 3).
// Scope is deliberately limited to hook config surfaces; skill/template bodies
// are covered by TestJournalFirstContentNamespaceConverged (Track 4).
func TestJournalFirstHookSurfacesConverged(t *testing.T) {
	root := repoRoot(t)

	hookSurfaces := []string{
		filepath.FromSlash("config/hooks.yaml"),
		filepath.FromSlash("plugins/loaf/hooks/hooks.json"),
		filepath.FromSlash("dist/cursor/hooks.json"),
		filepath.FromSlash("dist/opencode/plugins/hooks.ts"),
		filepath.FromSlash("dist/amp/.amp/plugins/loaf.ts"),
	}
	forbidden := []string{
		"loaf session start",
		"loaf session end",
		"loaf session log",
		"loaf session context",
		"session log --from-hook",
		"session log --detect-linear",
		"session context for-prompt",
		"session context for-compact",
		"session context for-resumption",
		"SessionEnd",
	}
	required := map[string]string{
		filepath.FromSlash("config/hooks.yaml"):            "loaf journal context --from-hook",
		filepath.FromSlash("plugins/loaf/hooks/hooks.json"): "journal context --from-hook",
	}

	var failures []string
	for _, rel := range hookSurfaces {
		path := filepath.Join(root, rel)
		if _, err := os.Stat(path); os.IsNotExist(err) {
			// dist artifacts are only present after a build; skip when absent.
			continue
		}
		failures = append(failures, forbiddenMatchesInFile(t, path, forbidden)...)
	}
	for rel, want := range required {
		path := filepath.Join(root, rel)
		body := readTextFile(t, path)
		if !strings.Contains(body, want) {
			failures = append(failures, filepath.ToSlash(rel)+": missing required journal-first command "+strconv.Quote(want))
		}
	}
	sort.Strings(failures)
	if len(failures) > 0 {
		t.Fatalf("journal-first hook surfaces not converged:\n%s", strings.Join(failures, "\n"))
	}
}

func forbiddenContentMatches(t *testing.T, path string, forbidden []string) []string {
	t.Helper()
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		t.Fatalf("Stat(%s) error = %v", path, err)
	}
	if !info.IsDir() {
		return forbiddenMatchesInFile(t, path, forbidden)
	}
	var matches []string
	err = filepath.WalkDir(path, func(file string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			name := entry.Name()
			if name == ".git" || name == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}
		if !entry.Type().IsRegular() || !isSessionConvergenceTextFile(file) {
			return nil
		}
		matches = append(matches, forbiddenMatchesInFile(t, file, forbidden)...)
		return nil
	})
	if err != nil {
		t.Fatalf("WalkDir(%s) error = %v", path, err)
	}
	return matches
}

func forbiddenMatchesInFile(t *testing.T, path string, forbidden []string) []string {
	t.Helper()
	body := readTextFile(t, path)
	lines := strings.Split(body, "\n")
	var matches []string
	for lineNumber, line := range lines {
		for _, phrase := range forbidden {
			if strings.Contains(line, phrase) {
				matches = append(matches, filepath.ToSlash(path)+":"+strconv.Itoa(lineNumber+1)+": "+phrase)
			}
		}
	}
	return matches
}

func readTextFile(t *testing.T, path string) string {
	t.Helper()
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%s) error = %v", path, err)
	}
	return string(body)
}

func isSessionConvergenceTextFile(path string) bool {
	switch filepath.Ext(path) {
	case ".md", ".yaml", ".yml", ".sh", ".py", ".json":
		return true
	default:
		return false
	}
}
